# Regenerates hub-codes.js from game HTML sources (hub embed = standalone false).
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

function Escape-ForJsString([string]$s) {
    $s = $s -replace '\\', '\\\\'
    $s = $s -replace '"', '\"'
    $s = $s -replace "`r`n", '\n'
    $s = $s -replace "`n", '\n'
    $s = $s -replace "`r", '\n'
    return $s
}

function Get-GameEmbed([string]$htmlPath, [string]$runFunc) {
    $raw = Get-Content -Raw -Encoding UTF8 $htmlPath
    if ($raw -notmatch '(?s)<script>\s*(.*?)\s*</script>') {
        throw "No script in $htmlPath"
    }
    $body = $Matches[1].Trim()
    # Hub: never standalone
    $body = $body -replace 'var\s+standalone\s*=\s*document\.body\.id\s*===\s*"[^"]+"\s*;', 'var standalone=false;'
    $body = $body -replace 'if\s*\(\s*standalone\s*\)\s*document\.body\.innerHTML\s*=\s*""\s*;', ''
    $body = $body -replace '\(\s*standalone\s*\?\s*document\.body\s*:\s*document\.documentElement\s*\)', 'document.documentElement'
    $body = $body -replace '\(standalone\?document\.body:document\.documentElement\)', 'document.documentElement'
    # Minify lightly
    $body = $body -replace '(?m)^\s+', ''
    $body = $body -replace '\s+', ' '
    return $body.Trim()
}

$games = @{
    ASTEROIDS_ON = 'asteroids.html'
    SANDBOX_ON   = 'sandbox.html'
    SNAKE_ON     = 'snake.html'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* Generated by build-hub.ps1 — do not edit by hand */')
[void]$sb.AppendLine('window.HUB_CODES = window.HUB_CODES || {};')
[void]$sb.AppendLine('(function(){')

foreach ($key in $games.Keys) {
    $path = Join-Path $root $games[$key]
    $code = Get-GameEmbed $path ''
    $esc = Escape-ForJsString $code
    [void]$sb.AppendLine("  HUB_CODES.$key = `"$esc`";")
}

[void]$sb.AppendLine('})();')

$out = Join-Path $root 'hub-codes.js'
[System.IO.File]::WriteAllText($out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $out ($((Get-Item $out).Length) bytes)"
